### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nyvs** [FastAlien/cpp-merge#5]
`RangeError: Maximum call stack size exceeded
    at readFile (/usr/lib/node_modules/cpp-merge/lib/parse/utils.js:31:15)
    at CppFileMerger.parseFile (/usr/lib/node_modules/cpp-merge/lib/parse/CppFileMerger.js:44:50)
    at CppFileMerger.parseIncludedFile (/usr/lib/node_modules/cpp-merge/lib/parse/CppFileMerger.js:68:21)
    at /usr/lib/node_modules/cpp-merge/lib/parse/CppFileMerger.js:49:25
    at Array.map (<anonymous>)
    at CppFileMerger.parseFile (/usr/lib/node_modules/cpp-merge/lib/parse/CppFileMerger.js:48:59)
    at CppFileMerger.parseIncludedFile (/usr/lib/node_modules/cpp-merge/lib/parse/CppFileMerger.js:68:21)
    at /usr/lib/node_modules/cpp-merge/lib/parse/CppFileMerger.js:49:25
    at Array.map (<anonymous>)
    at CppFileMerger.parseFile (/usr/lib/node_modules/cpp-merge/lib/parse/CppFileMerger.js:48:59)`

**Comment by FastAlien** [comment]
Hi, this error could be caused by circular includes. But it's only a guess. Without access to source files which caused this problem there not much I can do. Could you please attach example allowing to reproduce this issue?

**Comment by FastAlien** [comment]
I've reproduced and fixed this issue (660ecf760c01a07249505543674af5a2cbdd611b). Reported error shoudn't occur anymore but I can't guarantee that generated file will compile. This tool is not analyzing content of header and source files so it doesn't "understand" source code. You should fix circular dependencies in your project by moving common parts to separate header file. Thank you for reporting this problem.
